#!/usr/bin/env bash
# generate-secrets.sh — generate a .env file with cryptographically random secrets
#
# Usage:
#   bash scripts/generate-secrets.sh
#
# Creates .env in the project root. Refuses to overwrite an existing .env.
# After generation, review and customize COTURN_REALM and CLIENT_URL as needed.

set -euo pipefail

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  echo "Error: $ENV_FILE already exists."
  echo "Remove it first to regenerate: rm $ENV_FILE"
  exit 1
fi

# Verify openssl is available
if ! command -v openssl &>/dev/null; then
  echo "Error: openssl is required but not found."
  echo "Install it via your package manager (e.g., apt install openssl)."
  exit 1
fi

echo "Generating secrets..."

POSTGRES_PASSWORD=$(openssl rand -hex 16)
REDIS_PASSWORD=$(openssl rand -hex 16)
JWT_SECRET=$(openssl rand -hex 32)
JWT_REFRESH_SECRET=$(openssl rand -hex 32)
COOKIE_SECRET=$(openssl rand -hex 32)
COTURN_SECRET=$(openssl rand -hex 32)
MINIO_ROOT_PASSWORD=$(openssl rand -hex 16)

cat > "$ENV_FILE" <<EOF
# Generated by scripts/generate-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT THIS FILE

# ---------------------------------------------------------------------------
# PostgreSQL
# ---------------------------------------------------------------------------
POSTGRES_USER=tether
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=tether
DATABASE_URL=postgresql://tether:${POSTGRES_PASSWORD}@postgres:5432/tether

# ---------------------------------------------------------------------------
# Redis
# ---------------------------------------------------------------------------
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379

# ---------------------------------------------------------------------------
# JWT
# ---------------------------------------------------------------------------
JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}

# ---------------------------------------------------------------------------
# Cookie signing
# ---------------------------------------------------------------------------
COOKIE_SECRET=${COOKIE_SECRET}

# ---------------------------------------------------------------------------
# Coturn
# ---------------------------------------------------------------------------
COTURN_SECRET=${COTURN_SECRET}
COTURN_REALM=tether.local
COTURN_HOST=localhost

# ---------------------------------------------------------------------------
# MinIO
# ---------------------------------------------------------------------------
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------
CLIENT_URL=http://localhost
PORT=3001
EOF

echo "Generated ${ENV_FILE} with random secrets."
echo ""
echo "Next steps:"
echo "  1. Review and customize CLIENT_URL, COTURN_REALM, and COTURN_HOST for your environment."
echo "  2. Run: docker compose up"
echo ""
echo "WARNING: If you regenerate secrets after PostgreSQL has already been initialized,"
echo "         you must also remove the postgres volume to apply the new password:"
echo "           docker compose down && docker volume rm \$(docker volume ls -q | grep postgres_data) && docker compose up"
